### ISSUE TITLE
Line/ID as variable for condition

### ISSUE THREAD

**Issue by Joly0** [Jmgr/actiona#101]
Is it possible, to use the Line/ID of, for example Find Image action to calculate the Line/ID to go if found or not found. Something like If found goto ID of Action + 3

**Comment by Jmgr** [comment]
You mean getting the line of the current action? Sure. Use a piece of Code and `Script.nextLine`. See the [doc](https://wiki.actiona.tools/doku.php?id=en:code:core:script#line).
