### ISSUE TITLE
Les raccourcis clavier ne fonctionnent plus

### ISSUE THREAD

**Issue by Kanefalkai** [Jmgr/actiona#102]
Cela fait maintenant quelques mois que les raccourcis ne fonctionnent plus (pause, stop, etc).
Je suis sous Lubuntu (Ubuntu 18.04 (bionic))
------------------------------------------------------------
Actiona 3.9.2
Utilise Qt 5.9.1 (runtime 5.9.5) sous GNU/Linux (64 bit)
------------------------------------------------------------

Merci pour ce super logiciel !

**Comment by Jmgr** [comment]
Il me semble que cela fait partie des choses qui ont été corrigées dans la dernière version. Le problème est-il toujours présent dans la version 3.10.0?

**Comment by Jmgr** [comment]
Je ferme cette issue vu que ce bug devrait être corrigé dans la version 3.10.0. N'hésitez pas à ouvrir une autre issue si le problème persiste dans cette version.
