### ISSUE TITLE
Some random things

### ISSUE THREAD

**Issue by sombrakey** [Jmgr/actiona#103]
Hi, how to randomizer any things

Exemple:
Pause random in min 500ms and max 2000ms
Click mouse in min X position and max in Y position

Among other things that can be randomized.

**Comment by realgisam** [comment]
hi you can do it using javascript
ex:"https://forum.jmgr.net/viewtopic.php?f=35&t=9991
you can read the doc at https://wiki.actiona.tools/doku.php?id=en:code
