### ISSUE TITLE
Can't reach the website & forum anymore

### ISSUE THREAD

**Issue by xan2622** [Jmgr/actiona#107]
Hi

It seems that the website & forum are broken (down).

http://actiona.tools/ leads to a "Welcome to nginx!" message.
and 
https://www.jmgr.net/forum/index.php is down.

**Comment by Jmgr** [comment]
Hi, yes, there has been a hardware issue on the server hosting these websites and I am currently reinstalling everything. I expect to have finished by the end of the week-end. Sorry for the inconvenience.

**Comment by Jmgr** [comment]
Everything should be working again now. Don't hesitate to create a new issue if something is not working as it should.
