### ISSUE TITLE
Can't add script file to SFX archive and can't export my code

### ISSUE THREAD

**Issue by Xotia** [Jmgr/actiona#108]
Hi there, I'm a beginner on this soft so sorry if it's some stupid issues.

I create my script and when I want to create an .exe I have an error "Can't add script file to SFX archive" or "Impossible d'ajouter le fichier script à l'archive SFX" in french.

![image](https://user-images.githubusercontent.com/25925422/74968765-a5290300-541b-11ea-9183-da1e8c25fa33.png)

I was thinking about show you my code but after tested with an other basic code (1 clic) I have the same problem so I guess it's a problem from my computer, maybe some library uninstalled ?

By the way I have an other problem, when I try to export my code with a copy/paste in a text/code editor I'm having some syntax errors. It's simply a copy paste from a generated code so I don't understand where I can have theses syntax errors.

Thanks in advance.

**Comment by Jmgr** [comment]
Hi, it's not the first time I see this error, but I have never been able to pinpoint why this is happening. Not using Windows anymore also doesn't help. I'll have a look at the code and start a virtual machine at some point to try and fix this issue.

> By the way I have an other problem, when I try to export my code with a copy/paste in a text/code editor I'm having some syntax errors. It's simply a copy paste from a generated code so I don't understand where I can have theses syntax errors.

That's new. Could you provide a minimal example of code or text that triggers this error, please?

**Comment by Jmgr** [comment]
Also, in what directory have you saved your script file?

**Comment by Xotia** [comment]
Just Copy Paste a random click action :

`    <action name="ActionClick" comment="gauche">
            <exception id="2" action="1" line=""/>
            <exception id="0" action="0" line=""/>
            <exception id="1" action="0" line=""/>
            <exception id="32" action="0" line=""/>
            <exception id="33" action="0" line=""/>
            <parameter name="positionOffset">
                <subParameter name="value" code="0"></subParameter>
                <subParameter name="unit" code="0">0</subParameter>
            </parameter>
            <parameter name="button">
                <subParameter name="value" code="0">left</subParameter>
            </parameter>
            <parameter name="position">
                <subParameter name="value" code="0">101:266</subParameter>
                <subParameter name="unit" code="0">0</subParameter>
            </parameter>
            <parameter name="action">
                <subParameter name="value" code="0">pressRelease</subParameter>
            </parameter>
            <parameter name="amount">
                <subParameter name="value" code="0">1</subParameter>
            </parameter>
        </action>`

--> syntax errors found

I save all my scripts in D:\Sauvegarde\Actiona_needs\, just a personal disk where I save all my files.

**Comment by Jmgr** [comment]
> Just Copy Paste a random click action :

This is not Actiona "Code", meaning JavaScript, but some XML describing an action. Text/code editors can receive either raw text, or JavaScript. I see that this could be confusing, I should add some sort of check that could output some warning when XML is entered in a Code field.

> I save all my scripts in D:\Sauvegarde\Actiona_needs, just a personal disk where I save all my files.

Thanks. Despite my efforts I am still unable to reproduce the problem here. The script's contents are written in the user's temporary directory, an 7z archive is then copied there too. Then an archiving tool, 7zr.exe is called to add the script file to the archive, that is the part that is failing on your computer for an unknown reason.

Could you please start a console (`cmd.exe`), `cd` to where you have installed Actiona, go into the directory called `sfx` and then enter `7zr.exe`? That would allow us to know if there is an issue with this program on your computer.

**Comment by Xotia** [comment]
Sorry for my long response time.

> This is not Actiona "Code", meaning JavaScript, but some XML describing an action. Text/code editors can receive either raw text, or JavaScript. I see that this could be confusing, I should add some sort of check that could output some warning when XML is entered in a Code field.

I don't really understand what you mean, if I want to use the code option I need to use Javascript but not the Actiona code generated which is XML, am I right ?

> Thanks. Despite my efforts I am still unable to reproduce the problem here. The script's contents are written in the user's temporary directory, an 7z archive is then copied there too. Then an archiving tool, 7zr.exe is called to add the script file to the archive, that is the part that is failing on your computer for an unknown reason. Could you please start a console (cmd.exe), cd to where you have installed Actiona, go into the directory called sfx and then enter 7zr.exe? That would allow us to know if there is an issue with this program on your computer.

I get it, Actiona was installed in my disk where I install all my software (mainly). Here was the result of your cmd command.

![image](https://user-images.githubusercontent.com/25925422/78253196-51b6d400-74f4-11ea-9c4d-e0564b705636.png)

I uninstalled Actiona and installed it on the main disk (where Windows install) and it fix the problem, I can now create my .exe without issues. 

Thanks for your help. :)

**Comment by Jmgr** [comment]
> I don't really understand what you mean, if I want to use the code option I need to use Javascript but not the Actiona code generated which is XML, am I right ?

Yes, exactly. The XML is only used to describe a script (list of actions with their parameters).

> I uninstalled Actiona and installed it on the main disk (where Windows install) and it fix the problem, I can now create my .exe without issues.

Ah, that's very interesting. Programs usually don't have the same rights when installed into Program Files and somewhere else. Its good to know that this issue may be solved by installing Actiona in the default directory, and will help me reproduce the issue. Thank you very much. :+1: 

> Thanks for your help. :)

You are welcome :)
