### ISSUE TITLE
Not working on windows server 2019

### ISSUE THREAD

**Issue by mazbron** [Jmgr/actiona#110]
Hi,
I try to make bot automation using Actiona on my windows server 2019, everything is works well, but when I close my RDP, then actiona won't run.
Help me please.

Thanks

**Comment by Jmgr** [comment]
Hi,
Do you have the same issue with other programs? I don't have access to this operating system, so I can't try to reproduce this issue. I suspect that the OS freezes some UI components when no user is logged in.

**Comment by mazbron** [comment]
Hi,
I don't have issue with others program, maybe I can give you acces to my RDP?
So you can investigate the issue.
Or I should use Actiona 32bit version? 
Your download link in actiona.tools is dead btw.

Thanks

**Comment by mazbron** [comment]
> I haven't found any specific procedure for an application to be allowed to stay open. Basically, if you only disconnect the applications should stay open for a specific time depending on the value of `Session Time Limits` in the Windows configuration. If you log off however, all applications should be closed immediately. If you open another program (like Notepad) and disconnect, Actiona closes, but not Notepad?
Yep, My other bot (not click bot) still running when I close RDP.
I also running Actiona on my Linux RDP and it's works perfect even I close my RDP.
I try on Actiona on Windows for this week but have problem like that.
> Well if you don't mind I would prefer trying to solve this issue with you first. I wouldn't want to take any risk in breaking things.
Can you give me your email address?
I will send my RDP


Btw, I already make some money with your awesome tool, may I can donate for this project?
I did'nt find any donate page on your site.


Thanks

**Comment by Jmgr** [comment]
> Yep, My other bot (not click bot) still running when I close RDP.
I also running Actiona on my Linux RDP and it's works perfect even I close my RDP.
I try on Actiona on Windows for this week but have problem like that.

Alright, that seems to indicate a bug somewhere.

> Can you give me your email address?
I will send my RDP

I would rather not post it here (spam), but you can find it in Actiona's about box.

> Btw, I already make some money with your awesome tool, may I can donate for this project?
I did'nt find any donate page on your site.

That's nice, thanks ! There is a Sponsor button here on Github. For now it is using liberapay.com. Donation will be used to buy a code signing certificate for Actiona, which is needed for it to run on Windows 10 without needing admin rights (Microsoft has added some restrictions on programs emulating mouse/keyboard input). See more details [here](https://liberapay.com/Jmgr).

**Comment by Jmgr** [comment]
Have you found a solution to your issue, @mazbron?

**Comment by mazbron** [comment]
Hi @Jmgr ,
Nope, I discontinued using windows RDP.
I got litle problem, and I can't say here.
I will contact you soon via email.

Thanks
