### ISSUE TITLE
2 commands at the same time

### ISSUE THREAD

**Issue by sshmaxime** [Jmgr/actiona#113]
Hello, my problem is that i want to
```
press left control
+
double clic
```

There is no function to do that - or maybe i'm missing something.
If as I say, there is no way to do it that way, can I then execute 2 commands at the same time (one on the keyboard and the other one on the clic so no conflict) ? 

If I cannot do that either, then how can i do ? A fast reply would be appreciated 🙏 

Thank you very much for this software <3

**Comment by Jmgr** [comment]
Hi.
You can, use 3 actions:
- `Key` with `Left Control` as key and `Press` as action
- `Click` with action `Click` and amount 2
- `Key` with `Left Control` as key and `Release` as action

There is no action to only simulate a click unfortunately, so you will also have to specify a position where to click.
