### ISSUE TITLE
Putting html text into Clipboard with text/html MimeType

### ISSUE THREAD

**Issue by kjaval** [Jmgr/actiona#117]
Is there anyway to put some html text into clipboard with text/html mimetype
It would be good if sethtml method becomes available for clipboard object

**Comment by Jmgr** [comment]
Unfortunately there is currently no way to do that, but it would be simple enough to add. Thank you for the question, I will add that to the next release version.

**Comment by kjaval** [comment]
> Unfortunately there is currently no way to do that, but it would be simple enough to add. Thank you for the question, I will add that to the next release version.

Thanks for the reply.
On the other hand, I am not able to join the forum of Actiona.
It fails during registration. Your help is appreciated

**Comment by Jmgr** [comment]
> On the other hand, I am not able to join the forum of Actiona.
It fails during registration. Your help is appreciated

Hm, it seems that the Captcha is broken. Will fix that ASAP.
