### ISSUE TITLE
Requests Feature - Image/Color Recognition

### ISSUE THREAD

**Issue by MUWASEC** [Jmgr/actiona#119]
Is actiona can identify image by it's color ? i want to do some automation that need some image/color recognition so i don't need pause/wait before the action happen.

If not can u make those feature ? like for example take an image/color from x,y in the screen then compare it to our rules

**Comment by Jmgr** [comment]
There is an action to search for an image on the screen: `Find image`, see [here](https://wiki.actiona.tools/doku.php?id=en:actions:actionfindimage&s[]=find&s[]=image). Does that solve your issue?

**Comment by MUWASEC** [comment]
Yes, that clearly solve my problem. Hope actiona make some full documentation so it can help some beginner like me.

**Comment by Jmgr** [comment]
> Hope actiona make some full documentation with image so it can help some beginner like me.

I hope so, too! The issue is that I am the only developer on this project, so my time is limited. All contributions are welcome. :)
