### ISSUE TITLE
Can't find image on HDR screen

### ISSUE THREAD

**Issue by SullieLore** [Jmgr/actiona#122]
Hi team,

I've been trying to get image recognition working on a HDR screen. I tried setting the accuracy down to 45%, but still no luck.

Is there a workaround for this issue or is it able to be fixed?

Thanks,

Sullie

**Comment by Jmgr** [comment]
Hi,

I don't have such a screen available to reproduce the issue unfortunately.

What happens if you take a screenshot using Actiona? It's in `Tools -> Take screenshot`. Does a screenshot taken using this tool correct?

**Comment by SullieLore** [comment]
All good. I think I wasn't using the product correctly. Thanks for the awesome software. I hope it continues!

**Comment by Jmgr** [comment]
All right, thanks!
