### ISSUE TITLE
Unable to launch script with actexec

### ISSUE THREAD

**Issue by adembad** [Jmgr/actiona#123]
Hi, 

Unable to start a script with actexec on Debian 10 with Gnome. 
Just the message: "No text-to-speech plug-ins were found."

For info:
- the script don't use text-to-speech
- the package "libqt5texttospeech5" is installed

Beside, I tried to compile from source without success (dependency problem).

Thanks.

Alex.

**Comment by Jmgr** [comment]
Hi,

> Unable to start a script with actexec on Debian 10 with Gnome.
Just the message: "No text-to-speech plug-ins were found."

Does it work when you run the script with Actiona itself? There is a place in the code that initializes a text to speech engine to look for available locales, but I am surprised that it would exit the program if no tts plugins are found.

> Beside, I tried to compile from source without success (dependency problem).

What dependency? Could you post the error message here please?
