### ISSUE TITLE
new option to get current mouse location and setting a variable to it

### ISSUE THREAD

**Issue by sidmint** [Jmgr/actiona#129]
Hello, thanks for actiona.
I think it would be useful if there's an option to get current mouse location and set a variable to it so that it can be refered to later.
Idea came to me as the mouse moves to new location every time I run a script, is annoying if script is being run frequently, as in my case. By using this option I can bring back the mouse at the starting position at the end of script.
Please share your thoughts.
Thank you.

**Comment by Jmgr** [comment]
Hi, this is already possible: https://wiki.actiona.tools/doku.php?id=en:code:device:mouse&s[]=mouse#position

**Comment by sidmint** [comment]
Thank you for helping, and Actiona is wonderfull.
