### ISSUE TITLE
Can I start recording a macro with a shortcut?

### ISSUE THREAD

**Issue by ZacharieALES** [Jmgr/actiona#132]
With actiona is it possible to:
- start recording a macro with a command line? (without having the focus on actiona window)
- play a macro saved in a file with a command line? (idem)

Thank you.

**Comment by Jmgr** [comment]
> start recording a macro with a command line? (without having the focus on actiona window)

Macro recording is not a feature of Actiona (not yet anyway). I had multiple attempts at implementing that over the years but never got over the complexity of cross-platform key/mouse input recording.

> play a macro saved in a file with a command line? (idem)

You can start a script using the command line, yes: https://wiki.actiona.tools/doku.php?id=en:commandline&s[]=command&s[]=line
