### ISSUE TITLE
Code no functional

### ISSUE THREAD

**Issue by Gadgetroch** [Jmgr/actiona#134]
Good morning,

When i put that in code :+1: 

`var myObject = new Mouse();
myObject.click("MiddleButton");`

It made à left click, no middle.
I have the same issue with RightButton...

Can you help ?

Thank's

**Comment by Gadgetroch** [comment]
Up ?

**Comment by Jmgr** [comment]
Hi,

Try with `myObject.click(Mouse.MiddleButton)`
