### ISSUE TITLE
Script line 2: Cannot evaluate the value as an integer

### ISSUE THREAD

**Issue by lagrandeours** [Jmgr/actiona#136]
Hello 
i m trying to make a count down with a simple integer variable but
i have this message 
Script line 5: Cannot evaluate the value as an integer
what i m missing ? with this : 

thanks for your help

**$varQuestions-1**

<?xml version="1.0" encoding="UTF-8"?>
<scriptfile>
    <settings program="actiona" version="3.10.0" scriptVersion="1.1.0" os="Windows"/>
    <actions>
        <action name="ActionDataInput" version="1.0.0"/>
        <action name="ActionVariable" version="1.0.0"/>
    </actions>
    <parameters/>
    <resources/>
    <script pauseBefore="0" pauseAfter="0">
        <action name="ActionDataInput">
            <exception id="0" action="0" line=""/>
            <exception id="1" action="0" line=""/>
            <exception id="2" action="1" line=""/>
            <parameter name="dataType">
                <subParameter name="value" code="0">integer</subParameter>
            </parameter>
            <parameter name="defaultValue">
                <subParameter name="value" code="0"></subParameter>
            </parameter>
            <parameter name="editorType">
                <subParameter name="value" code="0">line</subParameter>
            </parameter>
            <parameter name="question">
                <subParameter name="value" code="0">nombre de question</subParameter>
            </parameter>
            <parameter name="variable">
                <subParameter name="value" code="0">varQuestions</subParameter>
            </parameter>
            <parameter name="windowIcon">
                <subParameter name="value" code="0"></subParameter>
            </parameter>
            <parameter name="windowTitle">
                <subParameter name="value" code="0"></subParameter>
            </parameter>
        </action>
        <action name="ActionVariable" pauseBefore="800">
            <exception id="0" action="0" line=""/>
            <exception id="1" action="0" line=""/>
            <exception id="2" action="1" line=""/>
            <exception id="32" action="0" line=""/>
            <parameter name="colorValue">
                <subParameter name="value" code="0"></subParameter>
            </parameter>
            <parameter name="positionValue">
                <subParameter name="unit" code="0">0</subParameter>
                <subParameter name="value" code="0"></subParameter>
            </parameter>
            <parameter name="type">
                <subParameter name="value" code="0">integer</subParameter>
            </parameter>
            <parameter name="value">
                <subParameter name="value" code="0">$varQuestions-1</subParameter>
            </parameter>
            <parameter name="variable">
                <subParameter name="value" code="0">nbrentier</subParameter>
            </parameter>
        </action>
    </script>
</scriptfile>

**Comment by lagrandeours** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<scriptfile>
    <settings program="actiona" version="3.10.0" scriptVersion="1.1.0" os="Windows"/>
    <actions>
        <action name="ActionDataInput" version="1.0.0"/>
        <action name="ActionVariable" version="1.0.0"/>
    </actions>
    <parameters/>
    <resources/>
    <script pauseBefore="0" pauseAfter="0">
        <action name="ActionDataInput">
            <exception id="0" action="0" line=""/>
            <exception id="1" action="0" line=""/>
            <exception id="2" action="1" line=""/>
            <parameter name="dataType">
                <subParameter name="value" code="0">integer</subParameter>
            </parameter>
            <parameter name="defaultValue">
                <subParameter name="value" code="0"></subParameter>
            </parameter>
            <parameter name="editorType">
                <subParameter name="value" code="0">line</subParameter>
            </parameter>
            <parameter name="question">
                <subParameter name="value" code="0">nombre de question</subParameter>
            </parameter>
            <parameter name="variable">
                <subParameter name="value" code="0">varQuestions</subParameter>
            </parameter>
            <parameter name="windowIcon">
                <subParameter name="value" code="0"></subParameter>
            </parameter>
            <parameter name="windowTitle">
                <subParameter name="value" code="0"></subParameter>
            </parameter>
        </action>
        <action name="ActionVariable" pauseBefore="800">
            <exception id="0" action="0" line=""/>
            <exception id="1" action="0" line=""/>
            <exception id="2" action="1" line=""/>
            <exception id="32" action="0" line=""/>
            <parameter name="colorValue">
                <subParameter name="value" code="0"></subParameter>
            </parameter>
            <parameter name="positionValue">
                <subParameter name="unit" code="0">0</subParameter>
                <subParameter name="value" code="0"></subParameter>
            </parameter>
            <parameter name="type">
                <subParameter name="value" code="0">integer</subParameter>
            </parameter>
            <parameter name="value">
                <subParameter name="value" code="0">$varQuestions-1</subParameter>
            </parameter>
            <parameter name="variable">
                <subParameter name="value" code="0">nbrentier</subParameter>
            </parameter>
        </action>
    </script>
</scriptfile>
`

**Comment by prudowicz** [comment]
Mark your variable value as code and then use: varQuestions - 1

```
<action name="ActionVariable" pauseBefore="800">
            <exception id="0" action="0" line=""/>
            <exception id="1" action="0" line=""/>
            <exception id="2" action="1" line=""/>
            <exception id="32" action="0" line=""/>
            <parameter name="colorValue">
                <subParameter name="value" code="0"></subParameter>
            </parameter>
            <parameter name="positionValue">
                <subParameter name="unit" code="0">0</subParameter>
                <subParameter name="value" code="0"></subParameter>
            </parameter>
            <parameter name="type">
                <subParameter name="value" code="0">integer</subParameter>
            </parameter>
            <parameter name="value">
                <subParameter name="value" code="1">varQuestions - 1</subParameter>
            </parameter>
            <parameter name="variable">
                <subParameter name="value" code="0">nbrentier</subParameter>
            </parameter>
        </action>
```
