### ISSUE TITLE
How to use multiple actiona at the same time X11 Display manager

### ISSUE THREAD

**Issue by xdien** [Jmgr/actiona#142]
I use vncserver with display manager as
DISPLAY = 1
DISPLAY = 2
When I run the script at DISPLAY 1, the script cannot be run at DISPLAY 2
##### Display session 1
```
DISPLAY=0.0.0.0:1 /usr/bin/actiona -s -t -Q -e -p -x myscript1.ascr
```
##### Display session 2 
```
DISPLAY=0.0.0.0:2 /usr/bin/actiona -s -t -Q -e -p -x myscript2.ascr
```
## Actiona version 3.9.2, script 1.1.0

**Comment by Jmgr** [comment]
If you are only running a script you should probable use `actexec` instead of `actiona`, as it is faster and can be run multiple times in parallel.

Opening another instance of Actiona will just make the window of the first instance be active, and the second instance will close itself.

**Comment by xdien** [comment]
thank you very much.  the problem has been resolved.
