### ISSUE TITLE
Faulting error

### ISSUE THREAD

**Issue by AkiraRiver** [Jmgr/actiona#148]
Hello there's the error with the last version x64 3.10 : 
"Faulting application name: actiona.exe, version: 3.10.0.0, time stamp: 0x5b4fbae1
Faulting module name: ActionPackSystem.dll, version: 0.0.0.0, time stamp: 0x5b4fbb79
Exception code: 0xc0000094
Fault offset: 0x0000000000011d63
Faulting process id: 0xb60
Faulting application start time: 0x01d71a477cda168d
Faulting application path: C:\Users\Mag\AppData\Local\Temp\7ZipSfx.000\actiona.exe
Faulting module path: C:\Users\Mag\AppData\Local\Temp\7ZipSfx.000\actions\ActionPackSystem.dll
Report Id: 7bc25fb4-b7d1-4e91-a34b-c2aad9622962
Faulting package full name: 
Faulting package-relative application ID:
Fault bucket 1475862872989928384, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: actiona.exe
P2: 3.10.0.0
P3: 5b4fbae1
P4: ActionPackSystem.dll
P5: 0.0.0.0
P6: 5b4fbb79
P7: c0000094
P8: 0000000000011d63
P9: 
P10: 

Attached files:
\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER19AB.tmp.dmp
\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1AF4.tmp.WERInternalMetadata.xml
\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1B14.tmp.xml
\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1B24.tmp.csv
\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1B54.tmp.txt

These files may be available here:
\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_actiona.exe_66c86153929710b799b5ea18aa41011eb44852_bb69349d_8c486230-9157-4754-b574-dc41484f0830

Analysis symbol: 
Rechecking for solution: 0
Report Id: 7bc25fb4-b7d1-4e91-a34b-c2aad9622962
Report Status: 268435456
Hashed bucket: f571cabc75122b86547b5176a9c08bc0
Cab Guid: 0"
She tried to install the previous version, this error does not appear but there's the keyboard script added in 3.10 that is missing.
Ty for help !

**Comment by Jmgr** [comment]
Hi, what version of Windows was this run on?

**Comment by AkiraRiver** [comment]
Win 10 pro ver : 10.0.1.19041 the latest one i guess

**Comment by Jmgr** [comment]
Thanks. Could send here the script that triggers this crash please? That way I cab try to reproduce the issue and fix it.
