### ISSUE TITLE
Fix the screenshoot wizard

### ISSUE THREAD

**Issue by Jmgr** [Jmgr/actiona#150]
The screenshot wizard is quite broken on Linux. If often takes a screenshot from the wrong screen, or just captures random pixels.

**Comment by Jmgr** [comment]
My plan here is to use the DBus interface of the specific desktop manager, like Gnome. That will also work on Wayland. The Qt screen grab would then only be used as a fallback.

**Comment by Nekotje** [comment]
When i use the find image the screen is always black when i click the capture button.
Using Ubuntu 21.04

**Comment by Jmgr** [comment]
The bug has been fixed, and the fix will be included in the next version.
