### ISSUE TITLE
How do I add variables

### ISSUE THREAD

**Issue by rbits0** [Jmgr/actiona#162]
I know this is a stupid question, but there's no information on how to use this. I want to do a very simple thing, add 2 variables together, but if I create a variable action and make the value $var1 + $var2 , with all the variables set to integer, it says "Cannot evaluate the value as an integer". The same happens with $var1 + 1 or 1 + 1. How do I add variables? And could you maybe add this to the wiki?

**Comment by Jmgr** [comment]
Try using the text field in code mode (the red triangle), then you can write `var1 + var2` directly. Variable insertion with `$` only allows insertions, nothing else. I'll have a look. I think what we are missing most is a tutorial for beginners in English. A friend of mine created a French version many years ago but that's it.
