### ISSUE TITLE
run multiple scripts at the same time? 

### ISSUE THREAD

**Issue by Fafa85** [Jmgr/actiona#164]
I explain the context to you, I play on minecraft and I have to vote to get rewards, I found a software that can automate the clicks to vote for me and I can vote 3 times 2h 3h and 24h and I would like to launch the 3 scripts at the same time but the software does not allow me so I would like to find a solution if you help me plz !

**Comment by Jmgr** [comment]
You can try using `actexec`, it allows you to run a script without any user interface. You can run multiple instances of it at the same time. Be careful not to have multiple scripts trying to control the keyboard or mouse at the same time, as this could lead to some unwanted behavior.
