### ISSUE TITLE
Focus on windows. not close

### ISSUE THREAD

**Issue by labaland** [Jmgr/actiona#171]
How do i "focus" on a spwcific window? i dont undertsand how to do it in this program? this is hhow it looks liks in macro recorder. but i want to use this program for other reseasons <3 :
![image](https://user-images.githubusercontent.com/20958435/161232282-00ab654a-375c-4a47-a1c1-0bd3f3110a7f.png)

**Comment by IntinteDAO** [comment]
Maybe maximize your game Window?

**Comment by Jmgr** [comment]
You can use a `Window` action, enter its name in the `Window title` field and select `Set foreground` as an action.
