### ISSUE TITLE
Trying to build on fedora actiona 

### ISSUE THREAD

**Issue by officialmiket** [Jmgr/actiona#173]
This is what i do. I cd into actiona then i do `qmake-qt5 -r` after this it just gives me the help page for qmake-qt5. If am doing something wrong i would appreciate help with my problem.

**Comment by Jmgr** [comment]
Actiona has migrated to cmake instead of qmake. Try with `mkdir build && cd build && cmake .. && make`.

**Comment by officialmiket** [comment]
Sorry for not replying earlier but this worked would be great if you could update the wiki with the new build instructions.
