### ISSUE TITLE
Question: can Actiona be uesed as replacment for Karabiner elements?

### ISSUE THREAD

**Issue by stoivo** [Jmgr/actiona#177]
Greetings 👋

I have a question. I could find any other channels to ask so I opened an issue. 
I used Karabiner elements on Mac OS to remap "play_or_pause" button to left. I want the same feature linux is that something Actiona can do?

**Comment by Jmgr** [comment]
Hi,

Actiona can wait for a key to be pressed and then press another one, but it cannot prevent the first key press from happening. You would end up with two key presses instead of one.

A more specialised tool might be a better fit here I think.

**Comment by stoivo** [comment]
Thanks, need to prevent `play_or_pause` from beeing triggered.

Any suggestions to which software can do this?

**Comment by Jmgr** [comment]
Not really sorry, never had to do that.
