### ISSUE TITLE
cmake .. on fedora

### ISSUE THREAD

**Issue by lanberg** [Jmgr/actiona#178]
When i Followed the build guides on you're website but when i type cmake .. it gives me an error of `-- Checking for one of the modules 'xtst'
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:890 (message):
  None of the required 'xtst' found
` and also says `-- Checking for one of the modules 'bluez'
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:890 (message):
  None of the required 'bluez' found
` 
what should i do i have tried downloading both but for some reason i can't download xtst atleast with dnf and also when i try to download bluez it just says package already installed. would like some help with this thank you.

**Comment by krillin666** [comment]
You have to install those package on Fedora probably

**Comment by krillin666** [comment]
However, even though I’ve installed every require package on Fedora. I’m getting an error when compiling:

```
[ 65%] Building CXX object actions/data/CMakeFiles/actionpackdata.dir/actionpackdata_autogen/mocs_compilation.cpp.o
In file included from /home/hidden/actiona/build/actions/data/actionpackdata_autogen/UVLADIE3JM/../../../../../actions/data/src/actions/writeinifiledefinition.hpp:24,
                 from /home/hidden/actiona/build/actions/data/actionpackdata_autogen/UVLADIE3JM/../../../../../actions/data/src/actionpackdata.hpp:26,
                 from /home/hidden/actiona/build/actions/data/actionpackdata_autogen/UVLADIE3JM/moc_actionpackdata.cpp:10,
                 from /home/hidden/actiona/build/actions/data/actionpackdata_autogen/mocs_compilation.cpp:2:
/home/hidden/actiona/build/actions/data/actionpackdata_autogen/UVLADIE3JM/../../../../../actions/data/src/actions/writeinifileinstance.hpp:24:10: fatal error: mini/ini.h: No such file or directory
   24 | #include "mini/ini.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [actions/data/CMakeFiles/actionpackdata.dir/build.make:96: actions/data/CMakeFiles/actionpackdata.dir/actionpackdata_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:711: actions/data/CMakeFiles/actionpackdata.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
  main  ~/actiona/build                                    
```

**Comment by lanberg** [comment]
This still a issue for me if anyone has any insight it would be helpful.

**Comment by jinithin** [comment]
fwiw i just built it successfully on fedora as well using the following packages:
`
cmake gcc-c++ qt5-qtbase-devel qt5-qttools-devel opencv-devel qt5-qtscript-devel qt5-qtxmlpatterns-devel qt5-qtx11extras-devel qt5-qttools-static bluez-libs-devel libnotify qt5-qtmultimedia-devel libnotify-devel libXtst-devel qt5-qtspeech-devel libxkbcommon-devel systemd-devel
`

**Comment by Jmgr** [comment]
Closing as resolved.
