### ISSUE TITLE
Addition

### ISSUE THREAD

**Issue by KevinMazelin** [Jmgr/actiona#180]
Hello everyone, 
i'm trying to loop action and increment variable. 
When i use "$loop+1" in value of action condition to check if equals it doesn't work with integer. 

Can you help me ?

**Comment by Jmgr** [comment]
Hi, that looks like a bug as this should definitely work. Thanks for the report.

**Comment by Jmgr** [comment]
Could you post a script as example please? It would help me to reproduce the issue. Thanks.
