### ISSUE TITLE
WTF happened to the website?

### ISSUE THREAD

**Issue by illtellyoulater** [Jmgr/actiona#184]
The link in the readme redirects to https://wiki.actiona.tools/doku.php which just shows some nonsense text.

**Comment by Jmgr** [comment]
Not sure what you mean, on my end that link just shows the usual Dokuwiki page. Could you take a screenshot if you still have this issue please?

**Comment by illtellyoulater** [comment]
@Jmgr this is what I see:

![image](https://user-images.githubusercontent.com/3078931/201535111-24ebfa28-814c-498a-a2cc-03e6e7c51182.png)

**Comment by illtellyoulater** [comment]
hey, any news on this??

**Comment by Jmgr** [comment]
Sorry about the delay. I can't reproduce this issue on any browser on my end. I guess you see the same result when visiting https://wiki.actiona.tools/doku.php?id=en:start ? (the browser's preferred language should be auto-detected but maybe that's failing for some reason).

I'll update the version of the wiki engine soon, not sure that will fix this issue but it's worth a try. I will also generate an offline pdf from the docs as a workaround.

**Comment by illtellyoulater** [comment]
Thank you, the link you provided works correctly, so yeah I guess it has to do with the browser language settings. 

Not sure if the following also affects the wiki page, but in my browser settings (I'm using Brave) I've chosen to *not* authorize the browser to communicate the OS language to web servers (when authorized, this would be used to allow web servers to automatically serve a page in the users' native language without the need to configure specific languages in the browser language settings).

**Comment by illtellyoulater** [comment]
Btw I just want to share that because many days have passed and I had to find an alternative solution, I ended using Power Automate from Microsoft. I was quite happy with it but it's not free nor OSS, however it has a free trial period which was enough for me to complete my task. That said, looking at its pricing page it doesn't look cheap at all... so I thought I'd just leave this note here in case you didn't know it and were looking for some inspiration for some new Actiona features ;)

**Comment by Jmgr** [comment]
> Thank you, the link you provided works correctly, so yeah I guess it has to do with the browser language settings.
> 
> Not sure if the following also affects the wiki page, but in my browser settings (I'm using Brave) I've chosen to _not_ authorize the browser to communicate the OS language to web servers (when authorized, this would be used to allow web servers to automatically serve a page in the users' native language without the need to configure specific languages in the browser language settings).

Ah that's good to know. I will try to find an update for the wiki plugin that automatically chooses the language, that's definitely a bug.

> Btw I just want to share that because many days have passed and I had to find an alternative solution, I ended using Power Automate from Microsoft. I was quite happy with it but it's not free nor OSS, however it has a free trial period which was enough for me to complete my task. That said, looking at its pricing page it doesn't look cheap at all... so I thought I'd just leave this note here in case you didn't know it and were looking for some inspiration for some new Actiona features ;)

Yeah sorry about that. Between me switching jobs and the holiday season it's not always easy to find time. Thanks, always good to see what features other similar apps have.
