### ISSUE TITLE
How to search for an image on a specific part of screen?

### ISSUE THREAD

**Issue by fmpanda** [Jmgr/actiona#186]
I want to search for an image (for ex: a button) but I don't need to search the whole screen. I know the specific area for that button. Sometime the button moves so I need to select a specific area for searching that button.
How can I do that?

**Comment by Jmgr** [comment]
This is currently not possible, Actiona doesn't provide a way to only take a screenshot of a part of the screen. Would be a good thing to add though.

**Comment by Jmgr** [comment]
Duplicated of https://github.com/Jmgr/actiona/issues/200
