### ISSUE TITLE
How to use arrays in .ini file?

### ISSUE THREAD

**Issue by FractalMind** [Jmgr/actiona#187]
I have to create a complex dance with excel sheets to simulate arrays.
How can you write/use arrays with .ini files?

I've tried:

```
[postal_code_list]
postal_code_list=[{"code":"test"}]
```
![Screenshot from 2022-12-05 12-45-02](https://user-images.githubusercontent.com/5481933/205706140-9ff3c17f-f514-425b-b72f-4f7a2885bca5.png)

No luck

**Comment by Jmgr** [comment]
Actiona relies on [mINI](https://github.com/pulzed/mINI) to interact with INI files, and it doesn't seem to support arrays AFAIK. The main issue is that INI is not formally defined, so every application has it's own way of doing things.
