### ISSUE TITLE
Something like ControlClick

### ISSUE THREAD

**Issue by lublak** [Jmgr/actiona#190]
Hi,
I come from Autohotkey.
But I find Autohotkey way too hard to use and found Actiona.
It seems much easier to use.
But now I am looking for a way to press a button.
Not pixel based but with text.
For example: Press a button with an inscription.
Currently it looks like only coordinates can be specified.

**Comment by Jmgr** [comment]
You could take a screenshot of that button and then use a FindImage action to find that image on the screen, store the result in a variable and then a Click action to click there.
