### ISSUE TITLE
Choosing a pixel color seems to not work properly for me

### ISSUE THREAD

**Issue by dawidpstrak** [Jmgr/actiona#199]
![image](https://github.com/Jmgr/actiona/assets/49794451/564ac891-7337-4b8d-a1b2-8c45968cb010)

When I try to select pixel, the pixel color output is wrong. Picker returns black in majority of cases or color that is not close to color on selected pixel.

I have this issue on Ubuntu 22.04 with Actiona v 3.10.1

**Comment by Jmgr** [comment]
Thanks for the bug report, I managed to reproduce it locally.

**Comment by dawidpstrak** [comment]
No problem, when i disabled my second monitor, feature worked well for me, so maybe it helps.

**Comment by Jmgr** [comment]
The bug has been fixed, and the fix will be included in the next version.
