### ISSUE TITLE
How to make dark theme?

### ISSUE THREAD

**Issue by uzayyli** [Jmgr/actiona#201]
It would be awesome if you could add dark theme option :) But if you are not interested in doing that, maybe can someone tell me what parts of code I need to edit and build a dark version myself?

Thanks!

**Comment by Jmgr** [comment]
I believe Qt should automatically adopt the theme color from the OS, but I'll have look.

**Comment by Jmgr** [comment]
Also, what is you operating system?

**Comment by Jmgr** [comment]
Marked as a feature: https://github.com/Jmgr/actiona/issues/128 so closing this one.

**Comment by uzayyli** [comment]
@Jmgr so sorry I didn't see your comments! I'm using Windows 10.
