### ISSUE TITLE
Add ScreenShot as a Standard Action

### ISSUE THREAD

**Issue by accessor-io** [Jmgr/actiona#213]
I request that screenshots are added as a preloaded action.
On Ubuntu and the keyboard I have, does not register the PrtSc key when requested to capture a key, using the 'key' action.
Can't find another solution to automate Screen Shots.

**Comment by gitvectors** [comment]
Flameshot in Ubuntu is one option by command line.

**Comment by Jmgr** [comment]
That's a good idea, and should not be very complicated to implement, too. Thanks.

**Comment by Jmgr** [comment]
Actually this is a duplicate of https://github.com/Jmgr/actiona/issues/205

**Comment by accessor-io** [comment]
are you on telegram?
