### ISSUE TITLE
outdated dependecies list

### ISSUE THREAD

**Issue by ggenellina** [Jmgr/actiona#220]
I'm on Ubuntu. I want to clone and build the latest Actiona version following the wiki instructions at [Get & compile the latest version](https://wiki.actiona.tools/doku.php?id=en:compilation&s[]=build)
When running `cmake ..` I get this error:

```
-- The CXX compiler identification is GNU 11.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at tools/CMakeLists.txt:36 (find_package):
  By not providing "FindQt6.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt6", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt6" (requested
  version 6.2) with any of the following names:

    Qt6Config.cmake
    qt6-config.cmake

  Add the installation prefix of "Qt6" to CMAKE_PREFIX_PATH or set "Qt6_DIR"
  to a directory containing one of the above files.  If "Qt6" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/gabriel/prog/actiona/build/CMakeFiles/CMakeOutput.log".
```

Dependencies listed in the wiki page include a lot of Qt5 libraries but apparently the project requires Qt6.

**Comment by Jmgr** [comment]
Good point, I recently upgraded Actiona to use Qt6 but did not update the docs. I'll update that asap. Thanks.

**Comment by Jmgr** [comment]
I have updated the [documentation](https://wiki.actiona.tools/doku.php?id=en:compilation), at least for Debian and derivatives. I hope this helps. Let me know if you have any issue building it.
