### ISSUE TITLE
openSUSE: libraries

### ISSUE THREAD

**Issue by DAP-DarkneSS** [Jmgr/actiona#28]
Hello.

I decided to make an openSUSE package. I got a runtime error:
> Unable to load 1 action(s): 
> libActionPackData: "Cannot load library /usr/lib/actionaz/actions/libActionPackData.so: > (librudeconfig.so.1: cannot open shared object file: No such file or directory)"

%rpm -ql actionaz | grep  librudeconfig
/usr/lib/actionaz/librudeconfig.so.1
/usr/lib/actionaz/librudeconfig.so.1.0
/usr/lib/actionaz/librudeconfig.so.1.0.0

How can libraries directory be changed to set it to lib64 for x64 hosts?

**Comment by Jmgr** [comment]
librudeconfig has been removed since version 3.9.0; could you try again with this version and open another issue if needed?
