### ISSUE TITLE
Write text doesn't use the current keyboard layout

### ISSUE THREAD

**Issue by Glandos** [Jmgr/actiona#3]
Hi,

I'm using a BÉPO layout for my keyboard.
When using "Write text", the text is written using the QWERTY layout, so it's just garbage :)

**Comment by 3ruce** [comment]
I had the same problem, reverting to a US keyboard layout as per the XTestFakeKeyEvent function bug did the trick...

https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/837456

**Comment by Jmgr** [comment]
I'm closing this since this is a bug external to Actiona.
