### ISSUE TITLE
QtGUI members such as "QtDialog" not available in JavaScript. 

### ISSUE THREAD

**Issue by zvodd** [Jmgr/actiona#36]
Testing Actiona 3.8.0 under windows, this code example no longer works:
[Actiona Wiki: code:examples](https://wiki.actiona.tools/doku.php?id=en:code:examples)

Possibly related to ***&lt;actiona_install_directory&gt;\code\script\qtscript_gui.dll*** having file size of ***0 Bytes***.

**Comment by Jmgr** [comment]
Yes, this is a known bug in the Actiona Windows installer. This will be fixed in version 3.9.0, but in the meantime you can use the latest nightly build: https://actiona.tools/nightlies/ These should be stable and very close to what the 3.9.0 version will be.

**Comment by zvodd** [comment]
Cheers
