### ISSUE TITLE
Lignes de commande ne fonctionnent plus ? 

### ISSUE THREAD

**Issue by InfinityWebMe** [Jmgr/actiona#37]
Bonjour,

j'essaye d'utiliser les lignes de commande actiona ( https://wiki.actiona.tools/doku.php?id=en:commandline ) sur Windows mais soit je m'y prend mal soit elles bug :-/

Quand je fais un actiona -v, la console ne m'affiche rien et me permet d'executer une nouvelle commande.

Le but de final serait de réussir à lancer un script Actiona depuis un autre script Actiona mais pas miyen de le faire fonctionner jusque maintenant.

Avez vous une idée d'où pourrait venir le soucis ? 

J'ai fait les tests sur Windows 7 et 10 avec actiona 3.8 et 3.9

**Comment by Jmgr** [comment]
Bonjour,

C'est une limitation de Windows : un programme ne peut pas à la fois afficher des fenêtres et écrire du texte dans la console. Actiona n'a donc aucun moyen sous Windows d'écrire quelque chose lorsque vous l'appelez avec le paramètre -v. Néanmoins les paramètres de lancement devraient tout de même fonctionner. Le wiki devrait toutefois indiquer cette limitation.

Le plus simple pour exécuter un script par la ligne de commande est d'utiliser ActExec, qui est un programme fourni avec Actiona et qui permet d'exécuter des scripts plus rapidement et plus facilement : https://wiki.actiona.tools/doku.php?id=en:actexec
