### ISSUE TITLE
Package repository for Fedora

### ISSUE THREAD

**Issue by mkrawiec** [Jmgr/actiona#48]
Hi, If everybody is interested in Fedora packages, I just started maintaining a repo in Copr (Fedora's equivalent to Ubuntu PPAs) - https://copr.fedoraproject.org/coprs/mkrawiec/actiona/

Sorry for writing it on the bugtracker, but apparently forum activation is broken as I didn't get my email. So its actually a bug report as well :bug:

**Comment by Jmgr** [comment]
Nice, thanks!

I fixed the forum activation bug (activation is no longer required).
