### ISSUE TITLE
Building with QT5.6 fails

### ISSUE THREAD

**Issue by Vaelatern** [Jmgr/actiona#52]
https://travis-ci.org/voidlinux/void-packages/jobs/128766086#L3401

This is in a test environment for the Void Linux repos. The version of QT5 that is present is, as my title states, 5.6.

**Comment by Vaelatern** [comment]
Linking this issue to voidlinux/void-packages#4062

**Comment by Jmgr** [comment]
Sorry for the late reply.
I can build Actiona successfully using Qt 5.6 on Ubuntu 14.04. A web search tends to indicate that this kind of error could be triggered by trying to compile a program using Qt 4. Other than that, no idea.

**Comment by Vaelatern** [comment]
Thank you, I'll try to confirm there are no qt4 traces.
