### ISSUE TITLE
Failed to start "Creating action dialog pixel color"

### ISSUE THREAD

**Issue by Clarin98** [Jmgr/actiona#64]
Actiona can't start. This is my terminal output (debian 9 - testing): 
```
(actiona:30457): GLib-GObject-WARNING **: cannot register existing type 'GtkWidget'

(actiona:30457): GLib-GObject-WARNING **: cannot add class private field to invalid type '<invalid>'

(actiona:30457): GLib-GObject-WARNING **: cannot add private field to invalid (non-instantiatable) type '<invalid>'

(actiona:30457): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(actiona:30457): GLib-GObject-WARNING **: cannot register existing type 'GtkBuildable'

(actiona:30457): GLib-GObject-CRITICAL **: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed

(actiona:30457): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(actiona:30457): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(actiona:30457): GLib-GObject-CRITICAL **: g_type_register_static: assertion 'parent_type > 0' failed

(actiona:30457): GLib-GObject-WARNING **: cannot add private field to invalid (non-instantiatable) type '<invalid>'
```

**Comment by Jmgr** [comment]
Thanks for the report and sorry for the late answer.

This is not an issue coming from Actiona but from Qt itself, they dropped support for Gtk based environments with Qt 5.7, but it should come back with Qt 5.8: https://bbs.archlinux.org/viewtopic.php?id=214147 This issue should be present in all applications using Qt.

Sadly you can only apply workarounds like using another window manager.

**Comment by mtcjayne** [comment]
Exactly what window managers "work" with this application? GNOME, GNOME Classic, and XFCE don't. I highly doubt KDE does since it's basically THE Qt window manager.

**Comment by Jmgr** [comment]
I just tested and can confirm that it works with Plasma (KDE). It seems that a fix for other window managers is to compile qt5ct and use it as a Qt theme instead of Gtk: https://github.com/mati75/qt5ct
There doesn't seem to be a package so a manual download and compilation is needed. It don't have the time to try it now but will do in the following days.

**Comment by mtcjayne** [comment]
Good to know. I'll also report back on Debian Testing eventually here. They
use what should be a fixed version of It and may be an acceptable option
for some current Debian Stable users.

**Comment by Jmgr** [comment]
Ok, good idea. I just tested and can confirm that compiling and using qt5ct as platform theme (following the instructions at [](https://github.com/mati75/qt5ct)) allows Actiona to start on Debian 9.

**Comment by jsmaniac** [comment]
From https://sparkylinux.org/qt-5-7-0-doesnt-support-gtk-theming/ :
```
sudo apt -y install qt5-style-plugins
QT_QPA_PLATFORMTHEME=gtk2 actiona
```

You might need to place the environment variable in `/etc/environment` and reboot (in my case simply prefixing it onto the `actiona` invocation was enough).

**Comment by 3ruce** [comment]
Thank you - that sorted it on Debian 9
