### ISSUE TITLE
Actiona will always find an image in a Chrome or VLC window, period

### ISSUE THREAD

**Issue by mtcjayne** [Jmgr/actiona#70]
When searching for the following test images in a full screen Chrome or VLC window playing a video that is only black screen, Actiona will **always** think it has found the image.

This means I cannot search videos for any visual markers.

[Images](https://imgur.com/a/mnuHt) are multiple pixels of solid color.

**Comment by mtcjayne** [comment]
No matter how large I make these solid-color images, I get the same result. Actiona thinksit has found the image regardless of whether or not it is present. Images that are not a single color do not do this.

Finding the color of a pixel isn't an option since I don't know where on the screen the marker will appear.

**Comment by Jmgr** [comment]
The search algorithm does not use color but only grayscale, this means that if you search for single color images then a black screen will always match.
