### ISSUE TITLE
Suggestion: Option that make it easy to see lines that have been executed.

### ISSUE THREAD

**Issue by ghost** [Jmgr/actiona#71]
Hi, thanks for this awesome program!
Is it possible to add an option to highlight executed lines to rapidly see where "jumps" are made?
Thx!

**Comment by Jmgr** [comment]
Hi, good idea! I could display some kind of "heat map" in the sense that after a script execution the background color of the actions change, varying from green to red, depending on the number of executions.

**Comment by Jmgr** [comment]
Added in branch 3.10 (commit 434c4a732652a000ee09cc2e51f8db4f7464c379)
