### ISSUE TITLE
Detect key press

### ISSUE THREAD

**Issue by xan2622** [Jmgr/actiona#72]
Hello.

There's one important feature that is currently missing in Actiona : **detect key press**.

If there was a way to detect keys used on the keyboard (as soon as they are pressed), it would allow many new possibilities of script creation.

Related forum post: 
https://www.jmgr.net/forum/viewtopic.php?f=30&p=14235#p14235

-------------------

Il y a actuellement une fonctionnalité qui manque cruellement dans Actiona: **la détection de touches du clavier**.

S'il y avait un moyen de détecter les touches qui sont utilisées sur le clavier (dès que l'utilisateur appuie sur elles), cela permettrait de nombreuses nouvelles possibilités de création de script.

J'espère vraiment que cette fonction puisse être ajoutée dans une prochaine version de Actiona.

**Comment by Jmgr** [comment]
Hi, and thanks for the idea. It has been suggested a few times. It's in the pipe for the next feature release, 3.10.

**Comment by Jmgr** [comment]
Added in version 3.10 as a new action: keyboard key condition. This action allows checking and waiting for a key combination to be pressed.
