### ISSUE TITLE
JavaScript scripts support

### ISSUE THREAD

**Issue by fro0m** [Jmgr/actiona#76]
Hi, thank you very much for Actiona.

I want to say that visual editing is not good for complex scripts as it is very complicated and does not allow hard references to code (only code lines).

Many developers wants to have ability to create automation scripts with `ecmaScript` code. From this code developer can call Actiona's functions i.e. findImage like `var pos = actiona.core.findImage(params)`

It will make Actiona the best automation tool ever.

**Comment by Jmgr** [comment]
Hi,

You can create a label by double-clicking on the line number at the left of the action's name. Enter a name for this label and press enter. You can now use the same name every time you need to "jump" on the line where the label is, even if the action's line number change.

Well you can already do this, just create a Javascript script file and run it by using the tool called "actexec". See the documentation [there](https://wiki.actiona.tools/doku.php?id=en:actexec). Almost every feature of Actiona can be used from Javascript, see the complete list [there](https://wiki.actiona.tools/doku.php?id=en:code).

For example, if you want to find an image in another image (a screenshot for instance) you can create an Image object and call [findSubImage](https://wiki.actiona.tools/doku.php?id=en:code:core:image#findsubimage) on it.

**Comment by Jmgr** [comment]
The main issue here is probably the lack of a complete tutorial, something where you can see Actiona's most used features, as not all of them are directly visible.

**Comment by nickpitlosh** [comment]
i for one am essentially guessing my way through this.
