### ISSUE TITLE
Find Image

### ISSUE THREAD

**Issue by mtcjayne** [Jmgr/actiona#80]
I am trying to search for two words of text in a large font size, but even at a confidence minimum of 1 Actiona cannot find it.

**Comment by Jmgr** [comment]
Could you please add an example of text (as an image) that you search for as an attached file?

**Comment by mtcjayne** [comment]
![image](https://user-images.githubusercontent.com/27238473/42291818-c7d5ad30-7f93-11e8-87f2-4f0c7177cf98.png)

**Comment by Jmgr** [comment]
Thanks. I cannot reproduce your issue: I can manage to find this image on my screen. I had to set the confidence minimum to 20 however. Other parameters have their default value. Does this work with these settings on your computer?
By the way, what version of Actiona are you using? And on which operating system?

**Comment by mtcjayne** [comment]
I was using 3.9.3 and I'll try your settings next week.
