### ISSUE TITLE
Problem with apply a click in a image previusy finded with "find image"

### ISSUE THREAD

**Issue by jrinconr** [Jmgr/actiona#81]
Hi
I'm trying to apply a click in a image previusy finded with "find image"

001
First in the "edit action of Find image" 
select 'window' in "source"
In Window name 'select the window target'
route to "Image  to find" 
"If found"   'goto line'  with the "click action"
Output parameters---- the name of the variable where to store the coordinates

002
Action Click (press and release)
Button Left
Position    ----- insert previous variable----
amount

error
Script line 2: "GG" is not a valid position.

How can I solve this?
The click with other coordinates works well when find the image.

Thanks a lot
And sorry for my english
![captura de pantalla de 2018-07-12 23-53-10](https://user-images.githubusercontent.com/22054761/42673017-ff53bcd8-862e-11e8-9db7-3f4ec11ff483.png)
![captura de pantalla de 2018-07-12 23-53-22](https://user-images.githubusercontent.com/22054761/42673023-052bd0b4-862f-11e8-879a-53ba7ece1087.png)

**Comment by Jmgr** [comment]
Hi, you have two options. You can:
1. Activate the _code mode_ in the _position_ field of the _click_ action by clicking on the red triangle. This activates Javascript evaluation when running the action ; your variable CG will then be evaluated and the result will then be sent to the action.
2. Write a dollar sign $ in front of the variable name. This indicates that this is a variable: its contents will then be inserted when the action in executed.

Note that you can insert a variable by clicking on the green arrow in any field: it will automatically add the dollar sign if needed.

**Comment by jrinconr** [comment]
Great!!
Thanks a lot
