### ISSUE TITLE
Build failure using opencv4

### ISSUE THREAD

**Issue by meanjollies** [Jmgr/actiona#90]
OpenCV 4.0 has recently released. This seems to include a lot of changes, which results in Actiona 3.10.0 failing to build. I have captured what I'm seeing here: https://gist.github.com/meanjollies/4d3139127cbf0662c613ad67f4f53ee2. I'm attempting to build this under Arch Linux. 

As an aside, for some reason, the pkgconfig opencv.pc file has been renamed to opencv4.pc. I'm not sure if that's a decision made by the Arch packager or if this is the new name going forward, but I needed to replace the value of unix:PKGCONFIG in actiontools/actiontools.pro from "opencv" to "opencv4" in order for qmake to succeed.

Please let me know if there's other info I can provide, and thank you for developing Actiona.

**Comment by Jmgr** [comment]
Thanks for the report, I fixed the compilation issues in commit fc7c2ef8d04eafcddbcd67f1a1e15af1127ca791, and added the PKGCONFIG_OPENCV qmake variable allowing to choose the name of the PKGCONFIG opencv package name (defaults to "opencv").

Does this fix your issues?

**Comment by meanjollies** [comment]
Yes! Life is good again. Thanks!
