### ISSUE TITLE
Loading/saving script window can't be dismissed

### ISSUE THREAD

**Issue by sojusnik** [Jmgr/actiona#96]
When switching to a recent script, the loading script window can't be dismissed, as shown [here](https://mega.nz/#!v5AAxQzC!jCcFjY4d-T6jVFcj1Ct3-oa0FO3t4UDb0zWP_3lP6lE). This window also pops-up and can't be closed, when a script is saved.

Happens with Actiona 3.9.4-1 from the Ubuntu 18.10 repository.

**Comment by Jmgr** [comment]
I think this has been solved in version 3.10.0. Could you try with this version if the problem is still present?

**Comment by Jmgr** [comment]
Should be fixed in version 3.10.0, so I'm closing this issue. Don't hesitate to create a new issue if the problem is still present in this version.
