### ISSUE TITLE
Click on previously found image.

### ISSUE THREAD

**Issue by damian212** [Jmgr/actiona#99]
Hello, i've been using actiona for quite some time now and its a wonderful tool. I would like some help though to click on a previously found image... Is this possible? I dont know anything about coding :/

**Comment by Jmgr** [comment]
Hi, it is possible:

In the Find Image action, enter the name of a variable where to store the position of the image that you are looking for in the **Position** field. For example "myPosition".

Create a Click action, and click on the green arrow on the right of the **Position** field, choose "Insert Variable" and select the name of the variable that you have entered earlier.

That's it :)

**Comment by troyrock** [comment]
How can I click instead on a point a set offset from the image that was found?  For instance if I wanted to click on the button below a specific text, I can't search for the button because it looks like all the other buttons but the text above the button is unique.  Thank you.

**Comment by Jmgr** [comment]
With some Code you could add the offset to the `myPosition` variable. See the doc regarding [point](https://wiki.actiona.tools/doku.php?id=en:code:core:point), `myPosition`'s type.

**Comment by Jmgr** [comment]
@troyrock, I'm closing this issue since the original question has been solved, but don't hesitate to create another issue if you have another question.
